### ISSUE TITLE
Multiple fields

### ISSUE THREAD

**Issue by jenstornell** [texnixe/kirby-related-pages#3]
Let's say I have this:

- Tags
- Categories
- Colors
- Brands
- Sizes

My product is `blue Lee jeans` and want the most relevant products for that. Instead of just listing all the jeans from the jeans category I probably want to see more Lee jeans or more blue jeans.

To combine them might seem like a big feature, but I think it would just be a counter, one for each match no matter the type. Then sort by that.

I my mind this along with a page method would make this plugin complete. Feedback?

**Comment by texnixe** [comment]
To be honest, for your use case, I'd rather use filters instead of a related pages plugin. It's rather intended for posts then for extensive product filtering. I know its not the same as something like "you might also like", but for the moment, I prefer to keep it simple. But I might consider it for the future.

Edit: And what would be the most relevant in your example? If color and size fit, but it is a shirt instead of a pair of jeans?

**Comment by jenstornell** [comment]
Then there needs to be a different kind of counter.

```
jeans - 1000p
blue - 10p
lee - 10p
```

**You could have 3 fixed/static levels for it:**

```php
c::set('plugin.related.pages.level1', array('category'));
c::set('plugin.related.pages.level2', array('color', 'brand'));
c::set('plugin.related.pages.level3', array('size'));
```

But it would indeed increase complexity.

**Comment by texnixe** [comment]
The thing is, this would still be static and not depending on what sort of filter categories the user has currently selected. So this would enhance complexity without resulting in a great algorithm.

For the moment, I will leave the plugin in its current state.

**Comment by texnixe** [comment]
This is now possible with the new [Kirby 3 Similar](https://github.com/texnixe/kirby3-similar) plugin.
